### PR TITLE
Fixes redux-saga compatibility

### PR DESCRIPTION
**Pull request by renanbandeira**
https://github.com/afitiskin/redux-saga-actions/issues/5

### CODE REVIEW

**Comment by afitiskin** [comment]
`all` effect has been introduced in `redux-saga` version 0.15.0, so we need to update `peerDependency` as well

**Comment by renanbandeira** [comment]
I just did it. I was fixing tests and I realized that it was neeeded.

**Comment by afitiskin** [comment]
@renanbandeira thank you very much!

**Comment by renanbandeira** [comment]
Thank you, @afitiskin ! Please, let me know if you are planning to upgrade it on npm

**Pull request merged**
